# Generated by Django 5.1.4 on 2025-01-20 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10, unique=True)),
                ('stops', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=10)),
                ('from_stop', models.CharField(max_length=100)),
                ('to_stop', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_amts_booking',
            },
        ),
        migrations.CreateModel(
            name='ActiveBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Unique identifier for active bus (e.g., '45-1', '45-2')", max_length=20, unique=True)),
                ('current_location', models.CharField(help_text='Current stop or location of the bus', max_length=100)),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('OUT_OF_SERVICE', 'Out of Service')], default='ON_TIME', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_instances', to='my_amts.bus')),
            ],
            options={
                'verbose_name': 'Active Bus',
                'verbose_name_plural': 'Active Buses',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.IntegerField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='my_amts.booking')),
            ],
            options={
                'db_table': 'my_amts_ticket',
            },
        ),
    ]
