# Generated by Django 5.1.4 on 2025-02-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_amts', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-search_time'], 'verbose_name_plural': 'Search histories'},
        ),
    ]
